--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: config; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA config;


ALTER SCHEMA config OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: channels; Type: TABLE; Schema: config; Owner: postgres
--

CREATE TABLE config.channels (
    channel_id character varying(40) NOT NULL,
    channel_name character varying(50),
    creation_ts timestamp without time zone DEFAULT now(),
    modified_ts timestamp without time zone DEFAULT now()
);


ALTER TABLE config.channels OWNER TO postgres;

--
-- Name: download_requests; Type: TABLE; Schema: config; Owner: postgres
--

CREATE TABLE config.download_requests (
    request_id integer NOT NULL,
    file_name character varying(50),
    status character varying(20),
    creation_ts timestamp without time zone DEFAULT now(),
    modified_ts timestamp without time zone DEFAULT now(),
    channel_id character varying(40),
    download_dir character varying(100)
);


ALTER TABLE config.download_requests OWNER TO postgres;

--
-- Name: download_requests_request_id_seq; Type: SEQUENCE; Schema: config; Owner: postgres
--

ALTER TABLE config.download_requests ALTER COLUMN request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME config.download_requests_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upload_requests; Type: TABLE; Schema: config; Owner: postgres
--

CREATE TABLE config.upload_requests (
    request_id integer NOT NULL,
    input_path character varying(100),
    file_name character varying(50),
    is_folder boolean,
    output_dir character varying(100),
    status character varying(20),
    creation_ts timestamp without time zone DEFAULT now(),
    modified_ts timestamp without time zone DEFAULT now(),
    channel_id character varying(40)
);


ALTER TABLE config.upload_requests OWNER TO postgres;

--
-- Name: upload_requests_request_id_seq; Type: SEQUENCE; Schema: config; Owner: postgres
--

ALTER TABLE config.upload_requests ALTER COLUMN request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME config.upload_requests_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploaded_files; Type: TABLE; Schema: config; Owner: postgres
--

CREATE TABLE config.uploaded_files (
    request_id integer,
    part_number integer,
    message_id character varying(40),
    creation_ts timestamp without time zone DEFAULT now(),
    modified_ts timestamp without time zone DEFAULT now()
);


ALTER TABLE config.uploaded_files OWNER TO postgres;

--
-- Name: channels channels_pkey; Type: CONSTRAINT; Schema: config; Owner: postgres
--

ALTER TABLE ONLY config.channels
    ADD CONSTRAINT channels_pkey PRIMARY KEY (channel_id);


--
-- Name: upload_requests upload_requests_pkey; Type: CONSTRAINT; Schema: config; Owner: postgres
--

ALTER TABLE ONLY config.upload_requests
    ADD CONSTRAINT upload_requests_pkey PRIMARY KEY (request_id);


--
-- Name: uploaded_files uploaded_files_request_id_fkey; Type: FK CONSTRAINT; Schema: config; Owner: postgres
--

ALTER TABLE ONLY config.uploaded_files
    ADD CONSTRAINT uploaded_files_request_id_fkey FOREIGN KEY (request_id) REFERENCES config.upload_requests(request_id);


--
-- PostgreSQL database dump complete
--

